version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    command:
      - redis-server
    env_file:
      ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  bot:
    build: .

    env_file:
      ./.env
    environment:
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - redis
